// Centralized project data used by Projects list and detail pages
// Images live under /public; use same image for both sides and grayscale the left

export const PROJECT_CATEGORIES = [
  { key: "TODOS", label: "TODOS" },
  { key: "HABITACIONAL", label: "HABITACIONAL" },
  { key: "COMERCIAL", label: "COMERCIAL" },
  { key: "INDUSTRIAL", label: "INDUSTRIAL" }
]

export const projectsData = [
  {
    id: "voala",
    slug: "voala",
    title: "VOALÁ",
    category: "COMERCIAL",
    location: "LEÓN, GTO. MÉXICO",
    architect: "MT3 Arquitectos",
    date: "AGOSTO 2024",
    startDate: "Noviembre 2023",
    endDate: "Agosto 2024",
    duration: "9 meses",
    landArea: "1261 m²",
    builtArea: "553 m²",
    levels: 2,
    concept: "AUTOLAVADO/CAFETERIA/SUSTENTABLE/CONTEMPORANEO/PREMIUM",
    description: "VOALA Autolavado es un proyecto innovador y sustentable que redefine la experiencia del cuidado automotriz en la ciudad. Su principal diferenciador es un sistema de reciclaje de agua con cuatro cisternas, que permite reutilizar el recurso de forma eficiente y elimina el desperdicio, posicionándose como un referente en sustentabilidad a nivel local y estatal.\n\nEl complejo está conformado por ocho islas de lavado automatizado, una zona de lavado a mano y, en el corazón del proyecto, una cafetería con acabados de alta gama, diseñada para que los clientes disfruten de un ambiente cómodo mientras esperan. El espacio cuenta con internet, música ambiental y sanitarios amplios, con especial atención a las necesidades de mujeres y familias con bebés, incluyendo áreas de cambio.\n\nEn la planta alta, una terraza abierta ofrece vistas tanto a un amplio jardín lateral como al diseño arquitectónico contemporáneo de las islas, aportando identidad y presencia al proyecto.",
    challenges: "El principal desafío fue integrar un sistema de reciclaje de agua de alta tecnología en un espacio comercial funcional, cumpliendo con normativas ambientales estrictas y optimizando el flujo de clientes. Se desarrolló un sistema modular de cisternas subterráneas que no interfiere con la operación diaria, con tratamiento de agua automatizado que permite reutilizar hasta el 90% del recurso, superando las expectativas de sustentabilidad y convirtiéndose en un modelo para futuros proyectos comerciales ecológicos.",
    materials: "Sistemas de reciclaje de agua con tecnología alemana de filtrado avanzado, pisos industriales de alta resistencia con acabado epoxi en zonas de lavado, acero inoxidable en estructuras metálicas y equipos, cerámica de gran formato en áreas de cafetería, y sistemas de iluminación LED de bajo consumo que resaltan la arquitectura contemporánea durante la noche.",
    image: "/voala/voala-2.webp",
    gallery: [
      { type: "image", src: "/voala/voala-1.webp" },
      { type: "image", src: "/voala/voala-10.webp" },
      { type: "image", src: "/voala/voala-3.webp" },
      { type: "image", src: "/voala/voala-4.webp" },
      { type: "image", src: "/voala/voala-5.webp" },
      { type: "image", src: "/voala/voala-6.webp" },
      { type: "image", src: "/voala/voala-13.webp" },
      { type: "image", src: "/voala/voala-14.webp" },
    ]
  },
  {
    id: "casa-esmeralda",
    slug: "casa-esmeralda",
    title: "CASA ESMERALDA",
    category: "HABITACIONAL",
    location: "LEÓN, GTO. MÉXICO",
    architect: "MT3 Arquitectos",
    date: "MARZO 2025",
    startDate: "Abril 2024",
    endDate: "Marzo 2025",
    duration: "11 meses",
    landArea: "160 m²",
    builtArea: "220 m²",
    levels: 2,
    concept: "OPEN SPACE/LOFT",
    description: "Un proyecto arquitectónico Casa-Residencial ubicado en el fraccionamiento Barrancas del Refugio, León, Gto. Es un proyecto ideal para personas solteras o parejas jóvenes que planean tener una familia pequeña, se enfoca en un concepto abierto, donde el corazón de la casa lo encuentras al inicio de tu recorrido, integrando la sala/comedor con la cocina, dando una apertura de vista hacia el fondo de la casa resaltando todo diseño y acabado arquitectónico.\n\nLa idea de esta casa fue crear espacios sin hacer divisiones, una integración general donde resuelves un terreno pequeño en un hogar familiar. El concepto de planta abierta maximiza la sensación de amplitud y facilita la convivencia, mientras que los acabados contemporáneos y la carpintería personalizada aportan carácter y calidez al proyecto.",
    challenges: "Un terreno muy débil, con mucha inclinación, excavación de tierra débil y refuerzo de esta. Casas existentes en los dos lados, se empezó de atrás para adelante con muy poco espacio complicando maniobras de construcción. La solución incluyó refuerzos estructurales especiales y una logística de construcción adaptada a las condiciones de acceso limitado.",
    materials: "La carpintería en puertas y muebles, toda la cancelería y cristales templados que aportan transparencia y continuidad visual entre los espacios. Acabados contemporáneos en pisos de alta resistencia y sistemas de iluminación integrados.",
    image: "/esmeralda/esmeralda-1.webp",
    gallery: [
      { type: "image", src: "/esmeralda/esmeralda-1.webp" },
      { type: "image", src: "/esmeralda/esmeralda-2.webp" },
      { type: "image", src: "/esmeralda/esmeralda-3.webp" },
      { type: "image", src: "/esmeralda/esmeralda-4.webp" },
      { type: "image", src: "/esmeralda/esmeralda-5.webp" },
      { type: "image", src: "/esmeralda/esmeralda-8.webp" },
      { type: "image", src: "/esmeralda/esmeralda-9.webp" },
      { type: "image", src: "/esmeralda/esmeralda-10.webp" },
    ]
  },
  {
    id: "molino-1-08",
    slug: "molino-1-08",
    title: "MOLINO 1-08",
    category: "HABITACIONAL",
    location: "LEÓN, GTO. MÉXICO",
    architect: "MT3 Arquitectos",
    date: "JUNIO 2025",
    startDate: "Febrero 2023",
    endDate: "Junio 2025",
    duration: "2 años 4 meses",
    landArea: "1200 m²",
    builtArea: "1200 m²",
    levels: 2,
    concept: "FAMILIAR/SOCIAL/LUJOSO/INTELIGENTE",
    description: "Un proyecto arquitectónico Casa-Residencial ubicado en el fraccionamiento El Molino Residencial & Golf, León, Gto. Una residencia de lujo con más de 1,200 m² de construcción, fue proyectada para una familia de 5 personas, consta de 4 recámaras con vista al campo de golf y un gym que en un futuro puede ser una 5ta habitación.\n\nEl proyecto te atrapa desde su diseño visual al ojo de cualquier usuario. Se prestó debido a las condiciones del terreno para poder diseñar 4 fachadas. Fachadas resueltas en base a la distribución arquitectónica, consta de elementos de doble altura, grandes volados de losa, pretiles con diseño y todo recubierto de algún acabado. Un proyecto con muchos espacios de convivencia ideal para una familia con niños que disfrutarán cada espacio de este.",
    challenges: "El terreno donde se ubica esta casa anteriormente era un terreno de cultivo y muy cerca de un arroyo por lo que demuestra es un terreno muy débil. Se hizo una excavación casi de 2 metros para poder crear una plataforma que mejoraría nuestro terreno y donde desplantamos esta casa. El proceso de consolidación del terreno fue fundamental para garantizar la estabilidad de una construcción de esta envergadura.",
    materials: "Piedras de mármol en muros, carpintería de parota natural en puerta principal y puertas abatibles, parota en volados, herrería en pretiles, louvers de PVC que regulan la entrada de luz natural y aportan privacidad sin comprometer las vistas al campo de golf.",
    image: "/molino_08/molino08-1.webp",
    gallery: [
      { type: "image", src: "/molino_08/molino08-1.webp" },
      { type: "image", src: "/molino_08/molino08-2.webp" },
    ]
  },
  {
    id: "casa-bosque-eterno",
    slug: "casa-bosque-eterno",
    title: "CASA BOSQUE ETERNO",
    category: "HABITACIONAL",
    location: "LEÓN, GTO. MÉXICO",
    architect: "MT3 Arquitectos",
    date: "SEPTIEMBRE 2022",
    startDate: "Diciembre 2020",
    endDate: "Septiembre 2022",
    duration: "1 año 9 meses",
    landArea: "673 m²",
    builtArea: "528 m²",
    levels: 2,
    concept: "NATURAL/CONTEMPORANEA/FAMILIAR",
    description: "Casa Bosque Eterno es un proyecto arquitectónico residencial ubicado en una zona privilegiada de León, Gto., que se distingue por su integración armónica con el entorno natural circundante. Esta residencia familiar fue concebida bajo el concepto de vivienda contemporánea que dialoga con la naturaleza, aprovechando las vistas hacia áreas verdes y creando espacios fluidos que borran los límites entre interior y exterior.\n\nEl diseño arquitectónico se caracteriza por volúmenes geométricos limpios y una paleta de colores que hace referencia al nombre del proyecto, incorporando tonos azulados en elementos específicos. La planta baja alberga los espacios sociales principales: sala, comedor, cocina integral y una terraza que se extiende hacia el jardín, creando un ambiente perfecto para la convivencia familiar.\n\nEn la planta alta se distribuyen cuatro recámaras principales, cada una con baño completo y amplios ventanales que capturan la esencia del bosque cercano.",
    challenges: "El terreno presentaba una vegetación densa preexistente y un desnivel considerable hacia la zona boscosa posterior, lo que representaba un desafío para la integración paisajística. Se desarrolló una estrategia de diseño que preservó la mayoría de los árboles existentes, creando plataformas elevadas que salvan el desnivel natural y generan vistas privilegiadas hacia el bosque, convirtiendo estas limitaciones topográficas en oportunidades para crear espacios únicos.",
    materials: "Piedra laja azul en muros exteriores que evoca el nombre del proyecto, carpintería de madera de encino en puertas y ventanas de gran formato, pisos de madera natural en áreas interiores, teja cerámica en cubiertas que se integra con el entorno boscoso, y elementos metálicos en color azul que acentúan la identidad del proyecto.",
    image: "/bosque_eterno/bosque-eterno-1.webp",
    gallery: [
      { type: "image", src: "/bosque_eterno/bosque-eterno-2.webp" },
      { type: "video", src: "/bosque_eterno/bosque-eterno.mp4", thumbnail: "/bosque_eterno/bosque-eterno-1.webp" },
    ]
  },
  {
    id: "molino-i-34",
    slug: "molino-i-34",
    title: "MOLINO I-34",
    category: "HABITACIONAL",
    location: "LEÓN, GTO. MÉXICO",
    architect: "MT3 Arquitectos",
    date: "ENERO 2025",
    startDate: "Febrero 2023",
    endDate: "Enero 2025",
    duration: "1 año 11 meses",
    landArea: "487 m²",
    builtArea: "410 m²",
    levels: 2,
    concept: "FAMILIAR/SOCIAL/CONTEMPORANEA",
    description: "Un proyecto arquitectónico Casa-Residencial ubicado en el exclusivo fraccionamiento El Molino Residencial & Golf, León, Gto. Esta residencia contemporánea fue diseñada para una familia joven que valora los espacios abiertos y la conexión con el entorno natural del campo de golf. El diseño se caracteriza por líneas limpias y modernas, con grandes ventanales que permiten la entrada abundante de luz natural y vistas panorámicas al paisaje exterior.\n\nLa distribución interior privilegia la integración de ambientes, con un área social amplia que combina sala, comedor y cocina en un concepto abierto. La planta alta alberga tres recámaras principales, cada una con baño completo y vestidor, además de una sala de televisión familiar. El jardín posterior se convierte en una extensión natural de los espacios interiores, con una terraza cubierta que invita a la convivencia al aire libre.",
    challenges: "El terreno presentaba una topografía irregular con pendiente hacia el campo de golf, lo que requería una nivelación cuidadosa para optimizar las vistas y el drenaje natural. Se implementó un sistema de muros de contención escalonados que no solo resolvieron el desafío técnico, sino que se convirtieron en elementos estéticos integrados al diseño paisajístico, creando terrazas naturales que mejoran la privacidad y la conexión visual con el entorno.",
    materials: "Piedra natural en muros exteriores que se integra con el paisaje, carpintería de madera tzalam en puertas principales y elementos decorativos, pisos de porcelanato de gran formato en áreas interiores, y sistemas de iluminación LED integrados que resaltan la arquitectura nocturna.",
    image: "/molino_i34/molinoi34-1.webp",
    gallery: [
      { type: "image", src: "/molino_i34/molinoi34-1.webp" },
      { type: "image", src: "/molino_i34/molinoi34-2.webp" },
      { type: "image", src: "/molino_i34/molinoi34-3.webp" },
      { type: "image", src: "/molino_i34/molinoi34-4.webp" },
      { type: "image", src: "/molino_i34/molinoi34-5.webp" },
      { type: "image", src: "/molino_i34/molinoi34-6.webp" },
      { type: "image", src: "/molino_i34/molinoi34-7.webp" },
      { type: "image", src: "/molino_i34/molinoi34-8.webp" },
      { type: "image", src: "/molino_i34/molinoi34-9.webp" },
      { type: "image", src: "/molino_i34/molinoi34-10.webp" },
      { type: "video", src: "/molino_i34/molinoi34.mp4", thumbnail: "/molino_i34/molinoi34-11.webp" }
    ]
  },
  {
    id: "molino-a16",
    slug: "molino-a16",
    title: "MOLINO A16 COND 12",
    category: "HABITACIONAL",
    location: "LEÓN, GTO. MÉXICO",
    architect: "",
    date: "AGOSTO 2023",
    startDate: "Noviembre 2021",
    endDate: "Agosto 2023",
    duration: "1 año 8 meses",
    landArea: "502 m²",
    builtArea: "481 m²",
    levels: "",
    concept: "",
    description: "El Proyecto A16 Molino se caracteriza por su arquitectura contemporánea y audaz, destacando un elemento central envolvente que abraza la puerta principal y se prolonga hasta la recámara principal, iluminado con un LED interior que refuerza su presencia. La fachada integra acabados en porcelanato, louver de madera y plafón cálido, con jardineras frontales y una cochera abierta para dos autos. La puerta principal, al cerrarse, genera un efecto visual de doble altura que aporta monumentalidad.\n\nAl ingresar, un vestíbulo con chimenea de doble vista conecta sala, comedor y acceso principal, mientras la escalera de madera se convierte en un remate escultórico. La sala y comedor se abren a una doble altura con un amplio ventanal que inunda de luz natural los espacios interiores y pasillos de planta alta. Al fondo, la cocina se vincula de manera flexible con la terraza, el jardín y la alberca, permitiendo integrar o independizar ambientes según la ocasión.\n\nEn planta alta se ubican tres recámaras, cada una con vestidor tipo walk-in closet y baño completo, conectadas por un pasillo que recorre la doble altura con vistas hacia el jardín interior, donde un olivo negro se erige como protagonista del diseño paisajístico, conectando lo interior con lo exterior.\n\nA16 Molino logra un balance entre diseño contemporáneo, funcionalidad y luminosidad, ofreciendo una residencia única dentro del exclusivo entorno de Molino Club de Golf.",
    challenges: "",
    materials: "",
    role: "Construcción, diseño y ejecución",
    image: "/molino_a16/molino_a16-1.webp",
    gallery: [
      { type: "image", src: "/molino_a16/molino_a16-1.webp" },
      { type: "image", src: "/molino_a16/molino_a16-2.webp" },
      { type: "image", src: "/molino_a16/molino_a16-3.webp" },
      { type: "image", src: "/molino_a16/molino_a16-4.webp" },
      { type: "image", src: "/molino_a16/molino_a16-5.webp" },
      { type: "image", src: "/molino_a16/molino_a16-6.webp" },
    ]
  },
]

export function findProjectBySlug(slug) {
  return projectsData.find(p => p.slug === slug)
}


